### ISSUE TITLE
Crypto Review Finding #3 Faulty implementation of curve arithmetic

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/SwiftECC#10]
## Vulnerability details
Any implementation of elliptic curves is based on the arithmetic operations, which are defined on the associated modular group. In particular, these include:
- Addition of two points
- Subtraction of two points
- Doubling of a point
- Multiplication of a point by a scalar
- Modular arithmetic operations of scalars

Unfortunately, the examined library makes some mistakes in this implementation, which can subsequently lead to erroneous results in signature verification. 

### Incorrect reduction with modular addition and subtraction
After the addition or subtraction of two scalars, the result must be reduced modularly to fall back into the expected value range. This is done by the library in a very simple way [1]:

```
func addModP(_ x: BInt, _ y: BInt) -> BInt {
  let z = x + y
  return z >= self.p ? z - self.p : z
}

func subModP(_ x: BInt, _ y: BInt) -> BInt {
  let z = x - y
  return z.isNegative ? z + self.p : z
 }
```

However, this reduction is only correct if both input parameters x and y were already in the expected range of values, i.e. 0 ≤ 𝑥 < 𝑝 as well as 0 ≤ 𝑦 < 𝑝 holds. However, this fact is not verified in the code.

### Missing point verification

In the methods the following methods of the `Domain` or `DomainP` classes, no point verification is performed at the beginning:

- double() (doubling of one point)
- add() (Addition of 2 points)
- subtract() (Subtraction of 2 points)
- negate() (Calculation of the inverse element)
- multiply() (multiplication of a point by a scalar)

This means that points can be passed as input parameters that are not on the curve at all. This can, especially in the context of the Elliptic Curve Diffie-Hellman (ECDHI) method, lead to a so-called Invalid Curve Attack [2].
The faulty methods look like the following [3]:

```
public func double(_ p: Point) -> Point {
 return self.characteristic2 ? self.domain2!.double(Point2.fromPoint(domain2!.rp, p)).toPoint() : self.domainP!.double(p)
}

public func add(_ p1: Point, _ p2: Point) -> Point {
 return self.characteristic2 ? self.domain2!.add(Point2.fromPoint(domain2!.rp, p1), Point2.fromPoint(domain2!.rp, p2)).toPoint() : self.domainP!.add(p1, p2)
}

public func subtract(_ p1: Point, _ p2: Point) -> Point { 
    return self.characteristic2 ? self.domain2!.subtract(Point2.fromPoint(domain2!.rp, p1), Point2.fromPoint(domain2!.rp, p2)).toPoint() : self.domainP!.subtract(p1, p2)
}

public func negate(_ p: Point) -> Point { 
    return self.characteristic2 ? self.domain2!.negate(Point2.fromPoint(domain2!.rp, p)).toPoint() : self.domainP!.negate(p) 
}

public func multiply(_ p: Point, _ n: BInt) -> Point { 
    return self.characteristic2 ? self.domain2!.multiply(Point2.fromPoint(domain2!.rp, p), n).toPoint() : self.domainP!.multiply(p, n)
}
```
Currently, such a check of the points (using the contains() method of the Domain class is only performed when decoding ASN.1 encoded points, but not when using manually instantiated points.

#### Incorrect reduction for modular addition and subtraction.
As a minimal solution, it should be checked at the beginning whether the input parameters fall within the expected range of values. It would be better to rely on the reduceModP reduction function already available in the same class here instead of a manual implementation, but this may be associated with speed losses.

#### Missing point verification
Before any arithmetic operation it must be ensured that the points passed as input parameter actually lie on the underlying elliptic curve.

**Comment by leif-ibsen** [comment]
As for the missing point on curve checks, they are now implemented in new methods:
   doublePoint, addPoints, subtractPoints, negatePoint and multiplyPoint
The old methods:
   double, add, subtract, negate and multiply
are now deprecated

As for incorrect modular reduction please see the comment in issue #11
