### ISSUE TITLE
Crypto Review Finding #14: Curve verification for signature verification could be improved

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/SwiftECC#14]
## Vulnerability details
Among other things, the constructor of the `ECSignature` class can be passed an object of type `Domain`, which is subsequently used for padding the two signature values [1]:
        
```
public convenience init(asn1: ASN1, domain: Domain) throws { 
    guard let seq = asn1 as? ASN1Sequence else {
        throw ECException.asn1Structure
    }

    if seq.getValue().count < 2 {
        throw ECException.asn1Structure 
    }
    
    guard let r0 = seq.get(0) as? ASN1Integer else {
        throw ECException.asn1Structure
    }
 
    guard let s1 = seq.get(1) as? ASN1Integer else {
        throw ECException.asn1Structure
    }    
    self.init(r: domain.align(r0.value.asMagnitudeBytes()), s:domain.align(s1.value.asMagnitudeBytes()))
}
```

However, the curve type obtained here is not stored in the class, but discarded after the constructor terminates. This leads to the fact that the signature can be checked unnoticed with an ECPublicKey object, which was created for another curve.
As long as the signature values in the constructor are not changed in content, this should not affect the result of the verification, but it leads to less efficient error detection.

## Countermeasures
If the curve specified in the constructor is stored within the class, then this value can be matched against the curve used for the key right at the start of the ECPublikKey.verify() method, and immediately terminated with a matching error if necessary.

## Severity: Info

References
[1] Source code of the constructor of the ECSignature class: https://github.com/leif-ibsen/SwiftECC/blob/621c70126966e5c289c4dc0ff801c6282b6baa05/Sources/SwiftECC/Signature.sw ift#L34

**Comment by leif-ibsen** [comment]
This has been fixed as proposed in release 2.1.0
