### ISSUE TITLE
Crypto Review Findings #16: Variable scope larger than necessary

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/SwiftECC#15]
## Vulnerability details
In the decode function of the Base64 class, x is declared outside the for loop, but is not needed across loop calls.
        
```
public static func decode(_ input: String) throws -> Bytes { 
    var bytes: Bytes = []
    var eq = 0
    var i = 0
    var x = 0
    var bbbb = Bytes(repeating: 0, count: 4) for s in input {
        x = Int(s.unicodeScalars.first!.value)
    [...]
    }
    if i > 0 {
        throw ECException.base64
    }
    return bytes
}
```
## Countermeasures
We recommend declaring the variable x inside the for loop. 

## References
[1] Source code of the decode function in the Base64 class: https://github.com/leif-ibsen/SwiftECC/blob/621c70126966e5c289c4dc0ff801c6282b6baa05/Sources/SwiftECC/Base64.swift #L104

**Comment by leif-ibsen** [comment]
Hardly a security issue, but fixed anyway in release 2.1.0
