### ISSUE TITLE
How to generate kDFout for the following Java functions? 

### ISSUE THREAD

**Issue by www036** [leif-ibsen/SwiftECC#17]
![image](https://user-images.githubusercontent.com/15873406/141440050-268f759e-046f-45b8-a630-e22791970da4.png)
![image](https://user-images.githubusercontent.com/15873406/141440935-2bac5a1a-cf97-46d7-9222-d9df4a0910cd.png)
I see that the Cipher class has the KDF method, but what are the meanings of the parameters S and R? How to pass?

**Comment by www036** [comment]
/**
     * Derive actual SecretKey with X9.63 KDF SHA-256
     *
     * @param initialSecret output from the ECDH agreement with Cofactor
     * @param sharedInfo    emphemeral public key from sender
     * @return shared secret of 32-bytes containing the 128-bit AES key and 16-byte
     * IV
     */
    private byte[] deriveX963KDFSHA256(byte[] initialSecret, byte[] sharedInfo, int outLen) {
        KDF2BytesGenerator kdfGenerator = new KDF2BytesGenerator(new SHA256Digest());
        kdfGenerator.init(new KDFParameters(initialSecret, sharedInfo));
        byte[] kdfOut = new byte[outLen];
        kdfGenerator.generateBytes(kdfOut, 0, outLen);
        return kdfOut;
    }


// X9.63 KDF functionality - please refer [SEC 1] section 3.6.1
    static func kdf(_ keySize: Int, _ macSize: Int, _ S: Bytes, _ R: Bytes) -> (key: Bytes, mac: Bytes) {
}

**Comment by leif-ibsen** [comment]
The 'kdf' function is internal to SwiftECC and not meant to be part of the API

**Comment by www036** [comment]
> 'kdf' 函数是 SwiftECC 的内部函数，并不意味着成为 API 的一部分

可以通过swiftecc去实现kdf吗? 我们想要使用swiftecc库
