### ISSUE TITLE
Xcode 13.0 support

### ISSUE THREAD

**Issue by jakob-fiegerl** [leif-ibsen/SwiftECC#19]
# What happened?
Currently when you want to upgrade from Xcode 12.* to Xcode 13.0 the SwiftECC library is not going to build due to the following message:

```
SwiftECC/Sources/SwiftECC/PrivateKey.swift:180:41:  integer literal '4294967295' overflows when stored into 'Int'
        if length >= mda.digestLength * 0xffffffff || length < 0 {
```

### Versions
- Xcode: 13.0
- SwiftECC: 2.2.0

**Comment by leif-ibsen** [comment]
As stated in README.md, SwiftECC requires that the Int and UInt types be 64 bit types. This seems not to be the case here which is the problem.
