### ISSUE TITLE
Dependency naming collision with other crypto lib

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/SwiftECC#23]
Hi Leif,

We are trying to use SwiftECC in the same project as [Shield](https://github.com/outfoxx/Shield).

Both have a sub-dependency to a package called `BigInt`.

Unfortunately, Swift Package Manager does not provide any ways to resolve this kind of ambiguity. See [here](https://forums.swift.org/t/cant-consume-two-swift-packages-with-the-same-name/40408) fore a similar issue.

Therefore, I wanted to ask if there is an option for you to refactor your `BigInt` dependency to a different name.

All the best,
Lorenz

**Comment by leif-ibsen** [comment]
Hi Lorenz,

once in a while I look at the GitHub figures for the number of clones of BigInt.
I don't have a total count (do you know how to get that?) but as far as I can tell,
it must be hundreds of people that are using BigInt.
Considering that, it wouldn't be right to suddenly change the package name.

A couple of ideas:

You have all the source code for BigInt, ASN1 and SwiftECC,
so in principle you could make the name change yourself.
Of course it would mean that you would have to do it again,
if there came a new release of SwiftECC that you wanted yo use.

As far as I can see, the Shield project is using the attaswift BigInt package.
Have they considered switching to my BigInt? - just joking.

I don't see a good and easy solution to this, sorry.
