### ISSUE TITLE
Integer literal '4294967295' overflows when stored into 'Int'

### ISSUE THREAD

**Issue by canry41341** [leif-ibsen/SwiftECC#24]
when archiving the project, the error "Integer literal '4294967295' overflows when stored into 'Int'" keep showing
xcode 13.3 on big sur
is there any way to solve this？
thank you！

**Comment by leif-ibsen** [comment]
Please make sure your 'Int' type is a 64 bit type. Try 

	print(Int.max)
	
it should print 9223372036854775807

If it prints 2147483647 'Int' is a 32 bit type

**Comment by canry41341** [comment]
Hi! thanks for you reply.
i did what you told me to do, and i came up with this:
Int.max = 9223372036854775807

then it means my app is running on 64bit right?

**Comment by leif-ibsen** [comment]
That is right

**Comment by canry41341** [comment]
if my app does run on 64bit, how come is that error keep showing up? i still don't have a clue :(

**Comment by leif-ibsen** [comment]
I don't know about your app and how it works.
Unless you can point to a place in SwiftECC where you believe there is a bug,
I can't help you, sorry.

**Comment by canry41341** [comment]
`
        let privateKeyBigInt = BigInt.BInt.init(magnitude: secp256k1PrivateKey.rawRepresentation.bytes)
        
        guard let secretInteger = BInt("\(privateKeyBigInt)") else {return}
        
        let eccPrivateKey = try ECPrivateKey.init(domain: Domain.instance(curve: .EC256k1), s: secretInteger)
        
        let eccPublicKey = try ECPublicKey.init(privateKey: eccPrivateKey)

        guard let messageData = verifyCode.data(using: .utf8) else {return}

        let eccsignature = privateKey.sign(msg: messageData)
`
here's all the codes that i used from swiftECC in my project, and i'm wondering if the problem was appeared on initial the BigInt to a ECPrivateKey

![截圖 2022-04-28 上午9 16 43](https://user-images.githubusercontent.com/26248983/165657688-37627807-68a1-471e-996b-8359fa4fe401.png)

And here is where the error occurs, it's in a function called 'keyAgreement'

**Comment by leif-ibsen** [comment]
I understand the error occurs when you try to build your application in Xcode.
The error has nothing to do with your actual code, it happens because the integer literal 0xffffffff
is too large for a 32 bit integer whereas it is perfectly ok for a 64 bit integer.
I am sure your 'Int' type is 32 bit. How and why that is, I can't help you with.
