### ISSUE TITLE
I have faced an issue with ECPrivateKey

### ISSUE THREAD

**Issue by Dimius555** [leif-ibsen/SwiftECC#26]
![photo_2022-05-06 12 19 42](https://user-images.githubusercontent.com/22593935/167104211-e96e9a31-7d52-4e18-be64-409aeba60026.jpeg)

**Comment by Dimius555** [comment]
error occurs when I make an archive build, in a case when I make debug build there is no issue

**Comment by Dimius555** [comment]
I'm not sure, but maybe make sense to add Cast as UInt32

**Comment by leif-ibsen** [comment]
The error happens because your 'Int' type is a 32 bit type (why that is, I don't know)
and the integer literal 0xffffffff is too large for a 32 bit type.
Please make sure your 'Int' type is 64 bit.

Please, also see issue #24.

**Comment by Dimius555** [comment]
Ok, thanks! I will review it. 

The problem happens only when I make an archive build. When I run the app on Simulator or Device - all is good. 
It's very strange...
