### ISSUE TITLE
'SymmetricKey' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by sergeybrazhnik-cb** [leif-ibsen/SwiftECC#28]
Version of lib: 3.5.0
Project with included library not compilling with this errors
![IMG](https://downloader.disk.yandex.ru/preview/b1d6fae1a8a886fcaacba099ca57ad90f58f50c132c85feb4065a173e29076e0/6399c534/zGqWYpxoaEpWGVobayTQsqnfkQn01oAvdUDYYnd_tUczDsr1Qb27Q4U521A8wRWqpZ3YPqulwbnC1LPfZAHAmg%3D%3D?uid=0&filename=2022-12-14_11-40-53.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048)

System and project settings
Xcode 14.1
Swift 5 (latests which is used in 14.1 xcode)
Base SDK in project 14.0 (CryptoKit is available)

Version 3.4.0 compiled fine!

**Comment by leif-ibsen** [comment]
I believe it has to do with how Xcode is configured.
Xcode must somehow be configured to use an iOS version less than 13.0.

**Comment by Developersimform** [comment]
Hey @leif-ibsen 

I guess there is no documentation in README for encryption/decryption with SymmetricKey.

I am struggling with encryption/decryption with use of SymmetricKey.
Could you please update the README ? 
Also Could you please add example?

Thank you
