### ISSUE TITLE
Allow Signature Bitwidth to  be different than Public Key Bitwidth

### ISSUE THREAD

**Issue by Preisschild** [leif-ibsen/SwiftECC#3]
Greetings,

In some cases, the signature BitWidth could be different from the Public Key Bitwitdh.

**Proposal**
Add an optional parameter to the `verify`-function to specify the Bidwith as an Integer.

**Comment by leif-ibsen** [comment]
Fixed in release 1.0.2

**Comment by Preisschild** [comment]
Thanks!

Seems to work fine
