### ISSUE TITLE
How to print hex string of the ECPublicKey

### ISSUE THREAD

**Issue by Mtczf** [leif-ibsen/SwiftECC#31]
Hi，The ECPublicKey generated by the private key, how to print the hex string of the public key？

**Comment by leif-ibsen** [comment]
A public ECC key is not just a number you can print.
It's a point on the elliptic curve with X and Y coordinates.

For example

    let d = Domain.instance(curve: .EC256r1)
    let (pub, priv) = d.makeKeyPair()
    
    // See the X and Y coordinates
    
    print(pub.w)
    
    // See the entire ASN1 encoding
    
    print(pub)
    
    // See X and Y in hex:
    
    print(pub.w.x.asString(radix: 16))
    print(pub.w.y.asString(radix: 16))


Point(9542059996965000465615725530698424199716080030810522789854535661434437729928, 5533450937872070643252673544704326007678577941668037466162233019705636415259)
Sequence (2):
  Sequence (2):
    Object Identifier: 1.2.840.10045.2.1
    Object Identifier: 1.2.840.10045.3.1.7
  Bit String (520): 00000100 00010101 00011000 10011101 01010100 01001111 01001001 00100011 10111100 10011010 01010000 00100001 01000111 00110011 11100010 10010100 10111010 11110010 11110011 00011000 10100011 00000101 01011111 10011110 01001100 10010010 00010100 00001011 01110111 11110100 01000001 01111110 10001000 00001100 00111011 11010010 01111110 10001000 01100110 11111111 11100011 00011101 00001111 01010010 10000111 00011000 00110111 00000101 11100110 10101101 11011101 10001000 01101100 01111010 10000100 10001101 11101100 10010111 11100001 10111000 11001100 00011101 10100111 11100111 00011011

15189d544f4923bc9a50214733e294baf2f318a3055f9e4c92140b77f4417e88
c3bd27e8866ffe31d0f5287183705e6addd886c7a848dec97e1b8cc1da7e71b

**Comment by Mtczf** [comment]
Thank you for your reply. I have another question to ask. The ECIESwithAES-CBC encryption in java sets the iv as a fixed value. I need to decrypt the data on the iOS side, but I can’t find a place to set the iv in this project

**Comment by Mtczf** [comment]
> Thank you for your reply. I have another question to ask. The ECIESwithAES-CBC encryption in java sets the iv as a fixed value. I need to decrypt the data on the iOS side, but I can’t find a place to set the iv in this project

oh，I have found it
