### ISSUE TITLE
Error in MessageDigest using sha1 algorithm

### ISSUE THREAD

**Issue by Mtczf** [leif-ibsen/SwiftECC#33]
Hi, when I tried to modify the source code, I found a problem. I need to use the sha1 algorithm to decrypt the data. The current MessageDigest uses the sha256 algorithm. When I modify it to sha1, the encryption and decryption will report an error, "Fatal error: Array index is out of range "
![1673942164467](https://user-images.githubusercontent.com/17916230/212840843-f6c19ba7-a210-413f-8327-2d3d39f931d3.jpg)

**Comment by leif-ibsen** [comment]
The workings of the X9.63 key derivation function is described in section 3.6.1 in

    Standards for Efficient Cryptography 1 (SEC 1), Certicom Corp. 2009

I think you need to read that if you want to change the code

**Comment by Mtczf** [comment]
thanks, i'll try
