### ISSUE TITLE
ECIES standard

### ISSUE THREAD

**Issue by Mtczf** [leif-ibsen/SwiftECC#35]
Hi，When I use bouncycastle to decrypt on the java side, iOS and java cannot decrypt each other.I want to know whether the ECIES standard in SwiftECC is ANSI X9.63 or IEEE 1363a？

**Comment by leif-ibsen** [comment]
The ECIES algorithm in SwiftECC uses the ANSI-X9.63-KDF key derivation function as it is described in 

    Standards for Efficient Cryptography 1 (SEC 1), Certicom Corp. 2009 - section 3.6.1

It uses the SHA2-256 message digest and it is compatible with the corresponding functionality in IBM's BlueECC product.
I have not read IEEE 1363a and I don't have access to it.

**Comment by Mtczf** [comment]
Thanks for your reply, saw it from the code. I have searched a lot of iOS encryption libraries during this time, but I can't find the same ECIES encryption scheme as java
