### ISSUE TITLE
what is the reasoning about having 3 implementations of Domain: Domain.swift/Domain2.swift/DomainP.swift

### ISSUE THREAD

**Issue by dabitdev** [leif-ibsen/SwiftECC#36]
I saw several implementations on different Domain files, but I have no clue what is the difference between them.

**Comment by leif-ibsen** [comment]
The Domain class is the only of the three classes with a public API, that is, visible to application code.

The DomainP class implements the logic related to prime characteristic domains.
The Domain2 class implements the logic related to characteristic 2 domains.

This is hidden for application code, that only sees the Domain API.

When a method in the Domain class is called, the call is forwarded to DomainP,
if the domain in question is a prime characteristic domain, and it is forwarded to Domain2,
if the domain in question is a characteristic 2 domain.

**Comment by dabitdev** [comment]
Hi Leif,
Thank you so much for your quick response. 
If you have some spare cycles, we would love having your contribution on the baseline.
Are you open to discuss a collaboration?

**Comment by leif-ibsen** [comment]
I'm not sure what kind of collaboration you mean.

If it means answering questions from time to time about the workings of SwiftECC, that's ok.

If it means actively developing code for whatever you are working on,
I'm afraid the answer is no.

**Comment by dabitdev** [comment]
I am looking for a quick paid collaboration -- we are stuck in iOS and we need some guidance to keep moving forward.

**Comment by leif-ibsen** [comment]
I'm afraid I can't help you. I have no experience with iOS whatsoever,
have never written any code for iOS. Sorry.

**Comment by dabitdev** [comment]
it is a swift not iOS ui related, I need to port this code from **java** code to **swift**
```
 val ecPublicKey = KeyFactory.getInstance(keyEntry.certificate.publicKey.algorithm)
 .generatePublic(X509EncodedKeySpec(keyEntry.certificate.publicKey.encoded)) as ECPublicKey

 val keyBytes =  EllipticCurves.pointEncode(EllipticCurves.CurveType.NIST_P256,
 EllipticCurves.PointFormatType.COMPRESSED, ecPublicKey.w));
```
        
so far what I tried with no luck is
```
let domain = Domain.instance(curve: .EC256r1)
let (pubKey, privKey) = domain.makeKeyPair()
let compressed = try pubKey!.domain.encodePoint(pubKey!.w, true)
keyBytes = compressed.toData()
```

**Comment by leif-ibsen** [comment]
Your code doesn't compile because of the two exclamationmarks. If you try something like

    let domain = Domain.instance(curve: .EC256r1)
    let (pubKey, privKey) = domain.makeKeyPair()
    let compressed = try domain.encodePoint(pubKey.w, true)
    print(compressed)

it will print something like

    [3, 37, 89, 41, 20, 186, 84, 139, 152, 116, 125, 101, 218, 30, 185, 246, 69, 7, 228, 46, 167, 159, 35, 13, 13, 93, 152, 61, 91, 71, 16, 68, 201]

**Comment by dabitdev** [comment]
Hi Leif,
the exclamations are Swift4 nullable logic, the problem is that the backed is not detecting this encoding as a valid compressed X509 public key.

**Comment by leif-ibsen** [comment]
Sorry, but I can't help you
