### ISSUE TITLE
Can I use it with Cocoapods?

### ISSUE THREAD

**Issue by Hank2354** [leif-ibsen/SwiftECC#37]
I would like to use this library through Cocoapods, why don't you want to add support for this? Cocoapods is the most popular dependency manager

**Comment by leif-ibsen** [comment]
I have no knowledge whatsoever about Cocoapods, so I wouldn't know how to add support for it

**Comment by Hank2354** [comment]
https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by leif-ibsen** [comment]
Thanks for your request for Cocoapods support, I appreciate your interest in SwiftECC.
As I said, I would need to learn about what Cocoapods is and how it works in order to support it.
Eventually, that might happen and so SwiftECC wiil support Cocoapods.
