### ISSUE TITLE
Decompression of EC key

### ISSUE THREAD

**Issue by apelt** [leif-ibsen/SwiftECC#38]
Nice lib. Could you also implement decompression of EC key? Meaning computation of Y coordinate if there is given only X coordinate with prefix (= compressed key).

**Comment by leif-ibsen** [comment]
I believe what you ask for is already implemented. For example

    let domain = Domain.instance(curve: .EC256r1)
    let (pubKey, _) = domain.makeKeyPair()
    let compressedPoint = try domain.encodePoint(pubKey.w, true)
    
'compressedPoint' is now the public key point encoded in compressed form. It can be decoded like

    let p = try domain.decodePoint(compressedPoint)
    let publicKey = try ECPublicKey(domain: domain, w: p)


'publicKey' is now the original pubKey

**Comment by apelt** [comment]
Ah, i missed that. It is. Thx!
