### ISSUE TITLE
Generating key agreement takes over 500ms

### ISSUE THREAD

**Issue by kaladivo** [leif-ibsen/SwiftECC#41]
How to reproduce: 

```swift
let domain256k1 = Domain.instance(curve: .EC256r1)

let k1 = domain256k1.makeKeyPair()
let k2 = domain256k1.makeKeyPair()

let from = DispatchTime.now().uptimeNanoseconds

try k1.1.keyAgreement(pubKey: k2.0, length: 32, md: .SHA1, sharedInfo: []) // 👈 here

let now = DispatchTime.now().uptimeNanoseconds
let fromNow = String(Double(now - from) / 1_000_000_000)
print("took: " + fromNow + " sec") // Running this on my M1 Max MacBook Pro prints `took: 0.534008709 sec`
```

The current implementation exhibits slower performance even compared to Javascript implementations such as crypto-browserify or the node:crypto package, which finish the task within a few milliseconds. Even Java implementation with BouncyCastle is faster

Upon exploring the code, it appears that [this line](https://github.com/leif-ibsen/SwiftECC/blob/55f34dd81338450d33c5665a4093538d17c5031e/Sources/SwiftECC/PrivateKey.swift#L508-L509). could be contributing to the slower performance.

**Comment by leif-ibsen** [comment]
On my iMac generating a key pair for domain EC256r1 takes about 780 milliseconds in debug mode and about 10 milliseconds in release mode. Maybe your code is running in debug mode and not in release mode.
