### ISSUE TITLE
How to export the base64 string after ECDSA signature?

### ISSUE THREAD

**Issue by Kejiasir** [leif-ibsen/SwiftECC#42]
```
func ecdsaSignature(_ params: String) {
        guard let privateKey = try? ECPrivateKey(pem: pkey) else {
            return
        }
        let message = params.data(using: .utf8)!
        let sig = privateKey.sign(msg: message)
        
        print(sig.description)
          
        let publicKey = ECPublicKey(privateKey: privateKey)
        let ok = publicKey.verify(signature: sig, msg: message)
        
        print(ok)
    }
```

**Comment by leif-ibsen** [comment]
Compute the base64 string like:

    let base64string = Base64.encode(sig.asn1.encode())

You could then recover the signature like (say your domain is 'dom'):

    let sig = try ECSignature(asn1: ASN1.build(Base64.decode(base64string)), domain: dom)

**Comment by Kejiasir** [comment]
#### Hello, thank you very much for your reply，Inconsistent result signed with `SwiftECC` and signed with `CryptoKit`? why?

#### SwiftECC Signature:
```
func ecdsaSignature(_ params: String) {
        guard let privateKey = try? ECPrivateKey(pem: pkey) else {
            return
        }
        let message = params.data(using: .utf8)!
        let sig = privateKey.sign(msg: message)
        
        let base64string = Base64.encode(sig.asn1.encode())
        print("SwiftECC: \(base64string)")
        
        let publicKey = ECPublicKey(privateKey: privateKey)
        let ok = publicKey.verify(signature: sig, msg: message)
        print("SwiftECC: \(ok)")
    }
```
#### Print:
```
SwiftECC: MEQCIDIEHOfhJiZ1G7tXpgL+9V2wGnQvbTZKXuctzMcDOYyWAiAZUN8gZ4/2Q+RWjFFo7C7Fxk8X
AE29uHSDLzaUpEl9tw==

SwiftECC: true
```


#### CryptoKit Signature:
```
func appleSignature(_ params: String) {
        if #available(iOS 14.0, *) {
            let messageDigest = params.data(using: .utf8)!
            let privateKey = try? P256.Signing.PrivateKey(pemRepresentation: pkey)
            
            guard let signature = try? privateKey?.signature(for: messageDigest) else { return }
            
            let signDataDerRepresentationBase64String = signature.derRepresentation.base64EncodedString()
            print("CryptoKit: \(signDataDerRepresentationBase64String)")
            
            let publicKey = privateKey?.publicKey
            let isValidSignature = publicKey?.isValidSignature(signature, for: messageDigest)
            print("CryptoKit: \(String(describing: isValidSignature))")
        }
    }
```
#### Print:
```
CryptoKit: MEYCIQC1/gY5nbXJGkQVNwU5Fhp0qfvHvot5sx5Z06b0ANk5IwIhAPZgIg2O4fuLwUtdtY2u78hViTcGBcRTOts/h36VRS+u

CryptoKit: Optional(true)
```

**Comment by leif-ibsen** [comment]
The signature algorithm is not deterministic.
That is, you will get different signatures each time you sign,
even with the same key and message.

Therefore, you can't expect SwiftECC and CryptoKit signatures to be identical,
even two SwiftECC signatures with the same key and message would be different.

In SwiftECC you have the option to generate deterministic signatures according to RFC-6979
by setting the 'deterministic' parameter to true in the sign operation.

I don't believe that option exists in CryptoKit.

**Comment by Kejiasir** [comment]
Thanks for your reply, you are correct.
 
I found that generating and verifying the signature takes almost 2 seconds, is there any room for optimization?

**Comment by leif-ibsen** [comment]
I tested sign and verify in Xcode with domain EC521r1.

They took together 2.6 secs in debug mode and 41 millisecs in release mode.

Maybe your measurement was run in debug mode?

**Comment by Kejiasir** [comment]
Yes, I test in debug mode, I verify in release mode. thank you
