### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Preisschild** [leif-ibsen/SwiftECC#5]
Hi,

Currently this project doesn't have a License. This makes it impossible to use in another app legally.
Could we add an License? 

**Proposal**
I think the MIT License would be good for this project, as it allows a bigger community to use this library.

We'd  just have to add a LICENSE document in the root with the [MIT License](https://choosealicense.com/licenses/mit/).

**Comment by leif-ibsen** [comment]
Just added MIT license

**Comment by Preisschild** [comment]
thanks
