### ISSUE TITLE
Support for curve25519

### ISSUE THREAD

**Issue by annathomasQB** [leif-ibsen/SwiftECC#7]
Hi,

is it possible to add curve25519 domain for creating the EC keys? 

I'm relatively new but this library has helped me so far. But our requirement is to implement Curve25519 encryption..  so please let me know how I can create a curve25519 domain public key.

**Comment by leif-ibsen** [comment]
Curve25519 has another form than the curves used in SwiftECC, so it can't be included in SwiftECC.

The SwiftEdDSA package supports Curve25519 for key creation and message signing and verification.
Perhaps you can use SwiftEdDSA?

**Comment by annathomasQB** [comment]
Will SwiftEdSA help give the public key in pem format ? like in SwiftECC

**Comment by leif-ibsen** [comment]
Yes, you can create public and private keys from their PEM encodings, and you can create the PEM encoding given a public or private key

**Comment by annathomasQB** [comment]
> Curve25519 has another form than the curves used in SwiftECC, so it can't be included in SwiftECC.
> 
> The SwiftEdDSA package supports Curve25519 for key creation and message signing and verification.
> Perhaps you can use SwiftEdDSA?

I just checked it out now. 
So I can create the key using ed25519(SwiftEDSA) and do encryption using Curve25519 (SwiftECC). That should work.. right?  I'll try and update here :)

**Comment by annathomasQB** [comment]
HI,

the signing algorithm uses ed25519 and not curve25519.. hence its not matching the requirement :(
