### ISSUE TITLE
Crypto Review Finding #1: Missing unit tests

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/SwiftECC#8]
### Vulnerability details

There are currently no or only incomplete unit tests for the following classes, which means that a faulty implementation would remain undetected currently or in the future.

#### SHA-2
The library uses its own implementation of the hash procedure SHA-2[1]. This is used, among other things, in the creation and validation of ECDSA signatures.

#### Arithmetic and signatures with Brainpool curves
For ECDSA signatures using Brainpool curves, there are no known-answer tests that can ensure the correctness of the procedure compared to other implementations.  There is only an attempt to re-verify data signed by the library itself.  Unfortunately, a verification of an externally created signature or a validation of the arithmetic does not take place.

#### SHA-2
All variants of the SHA-2 family should be subjected to rigorous unit testing within the library. 

#### Arithmetic and signatures with brainpool curves 

Both for the arithmetic of the curves (addition, scalar multiplication, ...) and for ECDSA signatures, unit tests should be created with externally validated test data.

In all cases, standardized test vectors should be used whenever possible [2] [3]. If no such vectors are available, test data should be created using established software from another vendor (e.g. OpenSSL).

[1] https://github.com/leif-ibsen/SwiftECC/blob/1.0.2/Sources/SwiftECC/Cipher/SHA2.swift

[2]NIST. The Secure Hash AlgorithmValidation System (SHAVS): https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Pro-gram/documents/shs/SHAVS.pdf

[3]L.Bruckert et.al. RFC 8734: ECC Brainpool Curves Test vectors: https://www.rfc-edi-tor.org/rfc/rfc8734#name-test-vectors

**Comment by leif-ibsen** [comment]
I'm looking into the three findings, and I will return with my comments soon - maybe in a few days

**Comment by leif-ibsen** [comment]
There are four new unit tests:
1) BrainpoolTest with test vectors from RFC8734
2) FuzzTest
3) SHA2Test with test vectors from http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA_All.pdf
4) VerifyTest with test vectors from the Wycheproof project
